"""Intial Migration

Revision ID: 97955ecf3e0b
Revises: 9acb98d689f6
Create Date: 2022-05-10 15:15:36.345264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97955ecf3e0b'
down_revision = '9acb98d689f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'username')
    # ### end Alembic commands ###
