"""Intial Migration

Revision ID: 9acb98d689f6
Revises: 3b267c458efb
Create Date: 2022-05-10 13:17:36.634302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acb98d689f6'
down_revision = '3b267c458efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###
