"""Intial Migration

Revision ID: a18cac73fcfe
Revises: 97955ecf3e0b
Create Date: 2022-05-10 16:45:17.881243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18cac73fcfe'
down_revision = '97955ecf3e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvote', sa.Boolean(), nullable=False))
    op.add_column('pitches', sa.Column('downvote', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'downvote')
    op.drop_column('pitches', 'upvote')
    # ### end Alembic commands ###
